import mysql.connector
import database_connection
baza = database_connection.konekcija()
myCursor = baza.cursor()


myCursor.execute("CREATE TABLE DATASET_1(ID int PRIMARY KEY NOT NULL AUTO_INCREMENT, DATASET int NOT NULL, CODE VARCHAR(20) NOT NULL, VALUE int NOT NULL, TIMESTAMP VARCHAR(100) NOT NULL)")
myCursor.execute("CREATE TABLE DATASET_2(ID int PRIMARY KEY NOT NULL AUTO_INCREMENT, DATASET int NOT NULL, CODE VARCHAR(20) NOT NULL, VALUE int NOT NULL, TIMESTAMP VARCHAR(100) NOT NULL)")
myCursor.execute("CREATE TABLE DATASET_3(ID int PRIMARY KEY NOT NULL AUTO_INCREMENT, DATASET int NOT NULL, CODE VARCHAR(20) NOT NULL, VALUE int NOT NULL, TIMESTAMP VARCHAR(100) NOT NULL)")
myCursor.execute("CREATE TABLE DATASET_4(ID int PRIMARY KEY NOT NULL AUTO_INCREMENT, DATASET int NOT NULL, CODE VARCHAR(20) NOT NULL, VALUE int NOT NULL, TIMESTAMP VARCHAR(100) NOT NULL)")

baza.commit()
